--Finding Registration date of users
SELECT
	USER_ID,
	MIN(ORDER_DATE) AS REG_DATE
FROM
	ORDERS
GROUP BY
	USER_ID
ORDER BY
	USER_ID;

--Finding the number of registered users per month
WITH
	REG_DATES AS (
		SELECT
			MIN(ORDER_DATE) AS REG_DATE,
			USER_ID
		FROM
			ORDERS
		GROUP BY
			USER_ID
	)
SELECT
	DATE_TRUNC('month', REG_DATE)::DATE AS FOODR_MONTH,
	COUNT(DISTINCT USER_ID) AS NEW_USERS
	FROM REG_DATES
GROUP BY
	FOODR_MONTH
ORDER BY
	FOODR_MONTH;

--Active user query
WITH
	REG_DATES AS (
		SELECT
			USER_ID,
			MIN(ORDER_DATE) AS REG_DATE
		FROM
			ORDERS
		GROUP BY
			USER_ID
	), REGISTRATIONS AS (
		SELECT
			DATE_TRUNC('month', REG_DATE)::DATE AS FOODR_MONTH,
			COUNT(DISTINCT USER_ID) AS REGS
		FROM
			REG_DATES
		GROUP BY
			FOODR_MONTH)
SELECT
	FOODR_MONTH,
	REGS,
	SUM(REGS) OVER (
		ORDER BY
			FOODR_MONTH ASC
	) AS REGS_RT
FROM REGISTRATIONS
ORDER BY
	FOODR_MONTH ASC
LIMIT
	5;