--Calculating Revenue
SELECT
	ORDER_ID,
	SUM(ORDER_QUANTITY * MEAL_PRICE) AS REVENUE
FROM meals
	JOIN ORDERS ON MEALS.MEAL_ID = ORDERS.MEAL_ID
GROUP BY
	orders.ORDER_ID ORDER BY REVENUE;
	SELECT * FROM stock;

--Calculating Cost
SELECT
	MEALS.MEAL_ID,
	SUM(MEAL_COST * STOCKED_QUANTITY) AS TOTAL_COST
FROM
	MEALS
	JOIN STOCK ON MEALS.MEAL_ID = STOCK.MEAL_ID
GROUP BY
	meals.meal_id
ORDER BY
	TOTAL_COST DESC
LIMIT 3;

--USING COMMON TABLE EXPRESSIONS
WITH
	COSTS_AND_QUANTITIES AS (
		SELECT
			MEALS.MEAL_ID, SUM(STOCKED_QUANTITY) AS QUANTITY,
			SUM(MEAL_COST * STOCKED_QUANTITY) AS TOTAL_COST
		FROM
			MEALS
			JOIN STOCK ON MEALS.MEAL_ID = STOCK.MEAL_ID
		GROUP BY
			MEALS.MEAL_ID
	)
SELECT
	MEAL_ID,
	QUANTITY,
	TOTAL_COST
FROM
	COSTS_AND_QUANTITIES
ORDER BY
	TOTAL_COST DESC
LIMIT
	5;

--BRINGING REVENUE AND COST TOGETHER AND CALCULATING PROFIT
WITH
	REVENUE AS (
		SELECT
			MEALS.MEAL_ID,
			SUM(ORDER_QUANTITY * MEAL_PRICE) AS REVENUE1
		FROM
			MEALS
			JOIN ORDERS ON MEALS.MEAL_ID = ORDERS.MEAL_ID
		GROUP BY
			MEALS.MEAL_ID
		ORDER BY
			REVENUE1
	),
	COST AS (
		SELECT
			MEALS.MEAL_ID,
			SUM(STOCKED_QUANTITY * MEAL_COST) AS TOTAL_COST
		FROM
			MEALS
			JOIN STOCK ON MEALS.MEAL_ID = STOCK.MEAL_ID
		GROUP BY
			MEALS.MEAL_ID
	)
SELECT
	REVENUE.MEAL_ID,
	REVENUE1,
	TOTAL_COST,
	REVENUE1 - TOTAL_COST AS PROFIT
FROM
	REVENUE JOIN COST ON REVENUE.MEAL_ID = COST.MEAL_ID
ORDER BY
	PROFIT DESC
LIMIT
	5;
