SELECT
	PRIME_MINISTERS.COUNTRY,
	PRIME_MINISTERS.CONTINENT,
	PRIME_MINISTER,
	PRESIDENT
FROM
	PRESIDENTS
	INNER JOIN PRIME_MINISTERS ON PRESIDENTS.COUNTRY = PRIME_MINISTERS.COUNTRY;

--INNER JOIN USING ALIASED TABLES
SELECT
	P2.COUNTRY,
	P2.CONTINENT,
	PRIME_MINISTER,
	PRESIDENT
FROM
	PRESIDENTS AS P1
	INNER JOIN PRIME_MINISTERS AS P2 ON P1.COUNTRY = P2.COUNTRY;

--INNER JOIN using USING
SELECT
	P2.COUNTRY,
	P2.CONTINENT,
	PRIME_MINISTER,
	PRESIDENT
FROM
	PRESIDENTS AS P1
	INNER JOIN PRIME_MINISTERS AS P2 USING (COUNTRY);

--Multiple INNER JOINS
SELECT
	*
FROM
	PRIME_MINISTERS
	INNER JOIN PRESIDENTS ON PRIME_MINISTERS.COUNTRY = PRESIDENTS.COUNTRY
	INNER JOIN STATES ON PRIME_MINISTERS.COUNTRY = STATES.COUNTRY;
